//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.WindowsAzure.Storage.Emulator.Controller {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.WindowsAzure.Storage.Emulator.Controller.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more initialization actions have failed. Resolve these errors before attempting to run the storage emulator again..
        /// </summary>
        internal static string ActionsFailed {
            get {
                return ResourceManager.GetString("ActionsFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization successful. The storage emulator is now ready for use..
        /// </summary>
        internal static string ActionsSucceeded {
            get {
                return ResourceManager.GetString("ActionsSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added database role for user {0}..
        /// </summary>
        internal static string AddedDatabaseRole {
            get {
                return ResourceManager.GetString("AddedDatabaseRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added reservation for {0} in user account {1}..
        /// </summary>
        internal static string AddedReservation {
            get {
                return ResourceManager.GetString("AddedReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adding database role for user {0}..
        /// </summary>
        internal static string AddingDatabaseRole {
            get {
                return ResourceManager.GetString("AddingDatabaseRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autodetect requested. Autodetecting SQL Instance to use..
        /// </summary>
        internal static string AutoDetectRequested {
            get {
                return ResourceManager.GetString("AutoDetectRequested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create folder &apos;{0}&apos; :&apos;{1}&apos;..
        /// </summary>
        internal static string CannotCreateFolder {
            get {
                return ResourceManager.GetString("CannotCreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking if database &apos;{0}&apos; exists on SQL instance &apos;{1}&apos;..
        /// </summary>
        internal static string CheckingDatabaseExists {
            get {
                return ResourceManager.GetString("CheckingDatabaseExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not detect if LocalDB is installed. To use LocalDB make sure LocalDB is installed and you have .NET 4.0.2 or higher installed..
        /// </summary>
        internal static string CouldNotDetectIfLocalDBIsInstalled {
            get {
                return ResourceManager.GetString("CouldNotDetectIfLocalDBIsInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating database {0} on SQL instance &apos;{1}&apos;..
        /// </summary>
        internal static string CreatingDatabase {
            get {
                return ResourceManager.GetString("CreatingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create database &apos;{0}&apos; : {1}..
        /// </summary>
        internal static string DatabaseCreationFailed {
            get {
                return ResourceManager.GetString("DatabaseCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find database &apos;{0}&apos;..
        /// </summary>
        internal static string DatabaseDoesNotExist {
            get {
                return ResourceManager.GetString("DatabaseDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure storage emulator initialization..
        /// </summary>
        internal static string DSInitCaption {
            get {
                return ResourceManager.GetString("DSInitCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage: DSService [/nogui] [/database:&lt;database for table service&gt;][/shutdown].
        /// </summary>
        internal static string DSServiceUsage {
            get {
                return ResourceManager.GetString("DSServiceUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dummy.
        /// </summary>
        internal static string Dummy {
            get {
                return ResourceManager.GetString("Dummy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty SQL Instance. Autodetecting SQL Instance to use..
        /// </summary>
        internal static string EmptyInstanceAutoDetecting {
            get {
                return ResourceManager.GetString("EmptyInstanceAutoDetecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An account with the same name already exists..
        /// </summary>
        internal static string EmulatorErrorMessageAccountAlreadyExists {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageAccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The specified account does not exist..
        /// </summary>
        internal static string EmulatorErrorMessageAccountNotFound {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageAccountNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage emulator is already running. Only one instance of the application can be run at the same time..
        /// </summary>
        internal static string EmulatorErrorMessageAlreadyRunning {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage emulator is already stopped..
        /// </summary>
        internal static string EmulatorErrorMessageAlreadyStopped {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageAlreadyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A default account cannot be deleted..
        /// </summary>
        internal static string EmulatorErrorMessageCannotDeleteDefaultAccount {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageCannotDeleteDefaultAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error parsing the command line..
        /// </summary>
        internal static string EmulatorErrorMessageCommandLineParsingFailed {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageCommandLineParsingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage emulator configuration file not found..
        /// </summary>
        internal static string EmulatorErrorMessageConfigNotFound {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageConfigNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find emulator components. Please verify the installation and repair if needed..
        /// </summary>
        internal static string EmulatorErrorMessageCorruptInstallation {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageCorruptInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create database..
        /// </summary>
        internal static string EmulatorErrorMessageDatabaseCreationFailed {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageDatabaseCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user data could not be cleared..
        /// </summary>
        internal static string EmulatorErrorMessageFailedToClearData {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageFailedToClearData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage emulator needs to be initialized. Please run the &apos;init&apos; command..
        /// </summary>
        internal static string EmulatorErrorMessageInitializationRequired {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageInitializationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create an account with the same name right after it was deleted..
        /// </summary>
        internal static string EmulatorErrorMessageNeedToWaitForAccountDeletion {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageNeedToWaitForAccountDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No available SQL Instance was found..
        /// </summary>
        internal static string EmulatorErrorMessageNoSqlInstanceFound {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageNoSqlInstanceFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reserve port..
        /// </summary>
        internal static string EmulatorErrorMessageReservationFailed {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageReservationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port reservation failed because of invalid user..
        /// </summary>
        internal static string EmulatorErrorMessageReservationFailedIncorrectUser {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageReservationFailedIncorrectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start the storage emulator..
        /// </summary>
        internal static string EmulatorErrorMessageStartFailed {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageStartFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage emulator is currently running. Please stop the storage emulator before retrying this operation..
        /// </summary>
        internal static string EmulatorErrorMessageStopRequired {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageStopRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error has occurred..
        /// </summary>
        internal static string EmulatorErrorMessageUnknownError {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageUnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User-specified instance not found. Please correct this and re-run initialization..
        /// </summary>
        internal static string EmulatorErrorMessageUserSpecifiedSqlInstanceNotFound {
            get {
                return ResourceManager.GetString("EmulatorErrorMessageUserSpecifiedSqlInstanceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot clean the database: {0}..
        /// </summary>
        internal static string ErrorCleaningDB {
            get {
                return ResourceManager.GetString("ErrorCleaningDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find the file &apos;{0}&apos; in the folder &apos;{1}&apos;..
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probing Failed. Retrying attempt {0} out of {1}..
        /// </summary>
        internal static string FormatRetryProbe {
            get {
                return ResourceManager.GetString("FormatRetryProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find file &apos;{0}&apos;. Please verify the installation and repair if needed..
        /// </summary>
        internal static string FormatUnableToFindFilePleaseVerifyInstall {
            get {
                return ResourceManager.GetString("FormatUnableToFindFilePleaseVerifyInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize Development Storage. Exit Code:.
        /// </summary>
        internal static string FormatUnableToInitializeStorageEmulatorWithExitCode {
            get {
                return ResourceManager.GetString("FormatUnableToInitializeStorageEmulatorWithExitCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found SQL Instance {0}..
        /// </summary>
        internal static string FoundSqlInstance {
            get {
                return ResourceManager.GetString("FoundSqlInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database access for user {0} was granted..
        /// </summary>
        internal static string GrantedDatabaseAccess {
            get {
                return ResourceManager.GetString("GrantedDatabaseAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Granting database access to user {0}..
        /// </summary>
        internal static string GrantingDatabaseAccess {
            get {
                return ResourceManager.GetString("GrantingDatabaseAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage emulator needs to perform some initialization that needs administrator rights. Do you want to continue ?.
        /// </summary>
        internal static string InitializationPrompt {
            get {
                return ResourceManager.GetString("InitializationPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;{0}&apos; is not a valid database name..
        /// </summary>
        internal static string InvalidDatabaseName {
            get {
                return ResourceManager.GetString("InvalidDatabaseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI &apos;{0}&apos; contained in the configuration is not valid..
        /// </summary>
        internal static string InvalidUri {
            get {
                return ResourceManager.GetString("InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URI &apos;{0}&apos; is not valid. The URI should be in the form &apos;http://127.0.0.1:&lt;port-number&gt;/&apos;..
        /// </summary>
        internal static string InvalidUri1 {
            get {
                return ResourceManager.GetString("InvalidUri1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Looking for a LocalDB Installation..
        /// </summary>
        internal static string LocalDBCheckForInstall {
            get {
                return ResourceManager.GetString("LocalDBCheckForInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LocalDB is installed but is not functioning properly. You may be missing prerequisites. Make sure you have .NET 4.0.2 or higher installed..
        /// </summary>
        internal static string LocalDBInstalledButNotRunning {
            get {
                return ResourceManager.GetString("LocalDBInstalledButNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found a LocalDB Installation..
        /// </summary>
        internal static string LocalDBInstallFound {
            get {
                return ResourceManager.GetString("LocalDBInstallFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find a LocalDB Installation..
        /// </summary>
        internal static string LocalDBInstallNotFound {
            get {
                return ResourceManager.GetString("LocalDBInstallNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure Storage Emulator.
        /// </summary>
        internal static string MessageboxTitle {
            get {
                return ResourceManager.GetString("MessageboxTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Did not receive ready signal from Storage Emulator..
        /// </summary>
        internal static string MessageDidNotReceiveReadySignalFromStorageEmulator {
            get {
                return ResourceManager.GetString("MessageDidNotReceiveReadySignalFromStorageEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start of Storage Emulator Failed..
        /// </summary>
        internal static string MessageStartOfStorageEmulatorFailed {
            get {
                return ResourceManager.GetString("MessageStartOfStorageEmulatorFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detect SQL Version..
        /// </summary>
        internal static string MessageUnableToDetectSqlVersion {
            get {
                return ResourceManager.GetString("MessageUnableToDetectSqlVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize Storage Emulator. Timed out..
        /// </summary>
        internal static string MessageUnableToInitializeStorageEmulatorTimedOut {
            get {
                return ResourceManager.GetString("MessageUnableToInitializeStorageEmulatorTimedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to open wait handle..
        /// </summary>
        internal static string MessageUnableToOpenWaitHandle {
            get {
                return ResourceManager.GetString("MessageUnableToOpenWaitHandle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to start Storage Emulator..
        /// </summary>
        internal static string MessageUnableToStartStorageEmulator {
            get {
                return ResourceManager.GetString("MessageUnableToStartStorageEmulator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user configuration file. Autodetecting SQL Instance to use..
        /// </summary>
        internal static string NoConfigurationAutoDetecting {
            get {
                return ResourceManager.GetString("NoConfigurationAutoDetecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probing SQL Instance: &apos;{0}&apos;..
        /// </summary>
        internal static string ProbingSqlInstance {
            get {
                return ResourceManager.GetString("ProbingSqlInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recreating database: &apos;{0}&apos;..
        /// </summary>
        internal static string RecreatingDatabase {
            get {
                return ResourceManager.GetString("RecreatingDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed reservation for {0} in user account {1}..
        /// </summary>
        internal static string RemovedReservation {
            get {
                return ResourceManager.GetString("RemovedReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reserve port: {0}..
        /// </summary>
        internal static string ReservationFailed {
            get {
                return ResourceManager.GetString("ReservationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reserve port because {0} is not a valid user: {1}..
        /// </summary>
        internal static string ReservationFailedIncorrectUser {
            get {
                return ResourceManager.GetString("ReservationFailedIncorrectUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset will delete all of the data stored in the local Microsoft Azure drive store. Are you sure you want to reset?.
        /// </summary>
        internal static string ResetAzureDrive {
            get {
                return ResourceManager.GetString("ResetAzureDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset will stop all the selected services and delete all the data stored by the services. Are you sure you want to reset?.
        /// </summary>
        internal static string ResetWarning {
            get {
                return ResourceManager.GetString("ResetWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempting to use server specified..
        /// </summary>
        internal static string ServerSpecified {
            get {
                return ResourceManager.GetString("ServerSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Microsoft Azure Storage Emulator.
        /// </summary>
        internal static string ShowUserInterfaceCaption {
            get {
                return ResourceManager.GetString("ShowUserInterfaceCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The graphical user interface for the Microsoft Azure Storage Emulator has been deprecated. The functionality is now provided by a new scriptable command line interface.
        ///
        ///Would you like to use the new command line interface or the old deprecated interface? Choose &quot;Help&quot; for more information..
        /// </summary>
        internal static string ShowUserInterfaceMessage {
            get {
                return ResourceManager.GetString("ShowUserInterfaceMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Command Line.
        /// </summary>
        internal static string ShowUserInterfaceNewButtonText {
            get {
                return ResourceManager.GetString("ShowUserInterfaceNewButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Interface.
        /// </summary>
        internal static string ShowUserInterfaceOldButtonText {
            get {
                return ResourceManager.GetString("ShowUserInterfaceOldButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start storage emulator. The SQL Server instance &apos;{0}&apos; could not be found. Configure the SQL Server instance for the storage emulator using the &apos;AzureStorageEmulator init&apos; command in the Microsoft Azure SDK..
        /// </summary>
        internal static string SqlInstanceError {
            get {
                return ResourceManager.GetString("SqlInstanceError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting storage emulator services....
        /// </summary>
        internal static string StartUp {
            get {
                return ResourceManager.GetString("StartUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage emulator is already running. Only one instance of the application can be run at the same time..
        /// </summary>
        internal static string StorageEmulatorAlreadyRunning {
            get {
                return ResourceManager.GetString("StorageEmulatorAlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage emulator is running..
        /// </summary>
        internal static string StorageEmulatorStillRunning {
            get {
                return ResourceManager.GetString("StorageEmulatorStillRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Azure SDK..
        /// </summary>
        internal static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The following services have been succesfully cleared of user data: {0}.
        /// </summary>
        internal static string SuccessClearFormat {
            get {
                return ResourceManager.GetString("SuccessClearFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been created.
        ///Account Name: {0}
        ///Primary Key: {1}
        ///Secondary Key: {2}
        ///Secondary Read Enabled: {3}.
        /// </summary>
        internal static string SuccessCreateAccount {
            get {
                return ResourceManager.GetString("SuccessCreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account {0} has been deleted..
        /// </summary>
        internal static string SuccessDeleteAccount {
            get {
                return ResourceManager.GetString("SuccessDeleteAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage emulator was successfully initialized and is ready to use..
        /// </summary>
        internal static string SuccessInit {
            get {
                return ResourceManager.GetString("SuccessInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account key for {0} has been regenerated.
        ///Primary Key: {1}
        ///Secondary Key: {2}.
        /// </summary>
        internal static string SuccessRegenerateKey {
            get {
                return ResourceManager.GetString("SuccessRegenerateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage emulator was successfully started..
        /// </summary>
        internal static string SuccessStart {
            get {
                return ResourceManager.GetString("SuccessStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The storage emulator was successfully stopped..
        /// </summary>
        internal static string SuccessStop {
            get {
                return ResourceManager.GetString("SuccessStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your account has been updated.
        ///Account Name: {0}
        ///Primary Key: {1}
        ///Secondary Key: {2}
        ///Secondary Read Enabled: {3}.
        /// </summary>
        internal static string SuccessUpdateAccount {
            get {
                return ResourceManager.GetString("SuccessUpdateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Storage Emulator.
        /// </summary>
        internal static string UICaption {
            get {
                return ResourceManager.GetString("UICaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot reset the local Microsoft Azure drive store. One or more of the files may be in use..
        /// </summary>
        internal static string UnableToResetAzureDrive {
            get {
                return ResourceManager.GetString("UnableToResetAzureDrive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The option is not valid: {0}.
        /// </summary>
        internal static string UnknownOption {
            get {
                return ResourceManager.GetString("UnknownOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User specified an instance through /server or /sqlInstance options..
        /// </summary>
        internal static string UserSpecifiedInstance {
            get {
                return ResourceManager.GetString("UserSpecifiedInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Probing failed. Retrying probe for user-specified instance..
        /// </summary>
        internal static string UserSpecifiedRetryProbe {
            get {
                return ResourceManager.GetString("UserSpecifiedRetryProbe", resourceCulture);
            }
        }
    }
}
